INSERT INTO translates (language, slug, value)
VALUES ('ENG', 'add-lesson-start', 'Add another lesson start'),
       ('ENG', 'add-another-day', 'Add another day for this time'),
       ('ENG', 'finish', 'I finish!'),
       ('ENG', 'change-lesson-duration', '♻ Change lesson duration'),
       ('ENG', 'next', '➡ Next'),
       ('ENG', 'add-another-day-and-time', '♻ Add another day and time'),
       ('ENG', 'done', '✅ Done!'),
       ('ENG', 'add-time-lesson', '🟢 Add time'),
       ('ENG', 'change-teacher-name', 'Change teacher''s name'),
       ('ENG', 'made-mistake-do-again', 'I made a mistake, lets do it again!'),
       ('ENG', 'delete-another-lesson-start', 'Delete another lesson start'),
       ('ENG', 'lesson-name', '📘 Lesson name: '),
       ('ENG', 'teacher-name', '🧑‍🏫 Teacher''s name: '),
       ('ENG', 'lesson-start-time', '🔔 Lesson start time: '),
       ('ENG', 'lesson-duration', 'Lesson duration: '),
       ('ENG', 'back', '⬅ Back'),
       ('ENG', 'change-time-lesson', '🟡 Change time'),
       ('ENG', 'try-again', 'Try again'),
       ('ENG', 'more', 'More'),
       ('ENG', 'no-lessons-for-the-day', 'There are no lessons for this day!'),
       ('ENG', 'what-lesson-edit', 'What lesson do you want to edit?'),
       ('ENG', 'choose-lesson-to-delete',
        'Look carefully at the name of the lesson and choose the one you want to delete.. 🟠🟠🟠'),
       ('ENG', 'what-interested-in', 'What are you interested in? 🙃'),
       ('ENG', 'menu', 'Highlighted the main menu buttons'),
       ('ENG', 'no-command', ', there is no such command!'),
       ('ENG', 'hello',
        '"Gaaarrr!" 😀 It means "Hello!" in pandas 😛 In our 🌳 forest everyone knows me, that is my job 🗂 When I was a child, I always liked to reconcile my sisters and brothers with each other,and sometimes with parents 😅 and today it has become my job and I continue to help parents and children to be friends. I love my job so much! 💖 Oh..Something I digress, in general, we will be friends with you! 🤝 Although I have fluffy 🐾 paws, it is still not difficult for me to help friends to do their household chores, I will remind you to do something,and then I will watch how my favorite friend coped with the task! And yes, sometimes your parents will check your work too! And I will keep your 💰 money! I am always ready to give them to your parents when you want it! You just need to press the ""Exchange!"" button. I am sure we will have fun! You can always write to me and I will answer you! I came up with special buttons for you so that it would be more convenient for you to write to me! I have cooked myself a juicy piece of bamboo and I am going to sit down 🍽 to eat, for now, look around here and remember that I will always answer when you call me!'),
       ('ENG', 'we-are-met', 'Hey! We''ve already met! Have you forgotten? 😅'),
       ('ENG', 'back-menu', 'We''re back at the main menu!'),
       ('ENG', 'enter-lesson-name',
        'Wow!😍 How I love new lessons!📙\nWhat is the name of the lesson you want to add?🤓'),
       ('ENG', 'enter-lesson-duration-again',
        'Let''s try to write the duration of the lesson again 🎈\n\nI constantly press the wrong buttons 🙃 you probably guessed why, because I have paws 🤪🐾'),
       ('ENG', 'enter-lesson-name-again',
        'Let''s try to write the name of the lesson again 🎈\n\nI constantly press the wrong buttons 🙃 you probably guessed why, because I have paws 🤪🐾'),
       ('ENG', 'enter-teacher-name-again',
        'Let''s try to write the name of the teacher again 🎈\n\nI constantly press the wrong buttons 🙃 you probably guessed why, because I have paws 🤪🐾'),
       ('ENG', 'show-lesson-on-specific-day', '😀 On which day of the week would you like to watch the lessons? 📚'),
       ('ENG', 'restore', '📚 Restore'),
       ('ENG', 'lesson', 'Lesson'),
       ('ENG', 'delete-lesson-part-2',
        ' removed! ✅\n\n If you made a mistake and deleted the wrong lesson, you can click the <b>Restore</b> button and I will return the lesson back ♟'),
       ('ENG', 'already-been-removed', ' removed! 🟢🟢🟢'),
       ('ENG', 'i-want-to-delete', '⚠️Yes, I want to delete '),
       ('ENG', 'back-to-lessons', 'No, take me back to the list of lessons 🙃'),
       ('ENG', 'make-sure-to-delete-lesson', 'Are you sure you want to delete this lesson?\n\n'),
       ('ENG', 'teacher', '🧑‍🏫 Teacher'),
       ('ENG', 'start-at', ':bell: Start at'),
       ('ENG', 'will-end-in', ':checkered_flag: Will end in'),
       ('ENG', 'duration', '⌚ Duration'),
       ('ENG', 'choose-time-to-remove', 'What time would you like to remove?'),
       ('ENG', 'remove-another-lesson-start', 'You can remove another start for the lesson'),
       ('ENG', 'just-be-careful', 'just be careful!'),
       ('ENG', 'edit-menu', '✂ This is schedule edit menu'),
       ('ENG', 'choose-lesson-to-change', 'What lesson would you like to change?'),
       ('ENG', 'enter-teacher-name', '🖊️ You can enter a new teacher name for the lesson'),
       ('ENG', 'edit-event-field', '🖊️ You can enter the desired name and replace the name'),
       ('ENG', 'what-time-for-lesson', '🖊️ What is the time for the lesson'),
       ('ENG', 'you-want-to-change', 'do you want to change?'),
       ('ENG', 'new-duration-for-lesson', 'Enter a new duration for this lesson'),
       ('ENG', 'option-for-start-time', 'What do you want to do with the start time of the lesson'),
       ('ENG', 'what-field-in-the-lesson', 'What field in the lesson'),
       ('ENG', 'want-to-fix', 'do you want to fix? 🪁'),
       ('ENG', 'back-to-schedule', 'added to your schedule again!🪀🪀 %0A%0A'),
       ('ENG', 'return-to-schedule', 'I have already added this lesson to your schedule, do not worry!'),
       ('ENG', 'day-for-the-lesson', '🌞🌝 What day of the week will the lesson take place?'),
       ('ENG', 'enter-time',
        'my favorite time for lessons is <b>11:20</b> or <b>08:00</b>, what time does the lesson start? 🕐'),
       ('ENG', 'save-day', 'Saved the day of the week!'),
       ('ENG', 'something-else-for-lesson', 'Maybe something else for the lesson'),
       ('ENG', 'added_day', '✅ Day added for lesson'),
       ('ENG', 'something-else-interesting', ' maybe something else interesting? 😃'),
       ('ENG', 'duration-of-lesson',
        'I know that you measure time in seconds, minutes and so on ⌚ But in our forest🌳 ' ||
        'we measure time a little differently, but I have long learned to use your hours and ' ||
        'completely understand how it works for you 😁 Therefore, lets write the duration of the' ||
        ' lesson in minutes, for example, <i>my favorite bamboo studio lesson lasted' ||
        ' <b>45</b> minutes</i>, and how many minutes lasts?'),
       ('ENG', 'choose-day-for-lesson', '🤗 Choose which day the lesson is'),
       ('ENG', 'start-the-same-time', 'starts at the same time 🕹️🕹️'),
       ('ENG', 'who-teaches', '🧑‍🏫 Who teaches'),
       ('ENG', 'enter-time-for-lesson', '🙂 You can write a new start time for the lesson'),
       ('ENG', 'time-already-add-for-lesson', '🛹 The new time has already been added for the lesson'),
       ('ENG', 'what-day-of-week', '🏓 Remind me what day of the week it is?'),
       ('ENG', 'lesson-was-save', 'The title of the lesson has been saved successfully! ✅ I am going to eat! 🍽️'),
       ('ENG', 'enter-new-time-for-lesson', 'You can enter a new time for the lesson'),
       ('ENG', 'start-time-changed', '✅ The start time of the lesson has changed!'),
       ('ENG', 'teacher-changed', '✅ 🧑‍🏫 Teacher changed!'),
       ('ENG', 'set-new-duration', 'New duration set for'),
       ('ENG', 'duration-for-lesson', 'Duration ⌚ for the lesson 📖'),
       ('ENG', 'add-lesson-start-time', 'Lets add a lesson start time 🟢'),
       ('ENG', 'lesson-added-to-schedule', 'Done! 😀 The lesson has been added to your schedule! 🗓️'),
       ('ENG', 'add-teacher-name-for-lesson', 'added! If you wrote without errors, then click the button <b>Next</b>'),
       ('ENG', 'smth-saved-check',
        'saved! ✅ If there are no mistakes in the name, lets go further! 🙂 click the button'),
       ('ENG', 'lesson-already-saved', 'This lesson has already been saved!'),
       ('ENG', 'starts-at', 'Starts at'),
       ('ENG', 'lesson-end-in', 'Will end in'),
       ('ENG', 'remove-time-lesson', 'Remove time'),
       ('ENG', 'add-new-lesson', '✅ Add new lesson'),
       ('ENG', 'edit-saved-lesson', '🛠 Edit an already saved lesson'),
       ('ENG', 'delete-lesson', '⚠️Delete lesson'),
       ('ENG', 'show-schedule-for', '💡 Show schedule for..'),
       ('ENG', 'edit-schedule', '🛠 Edit schedule'),
       ('ENG', 'delete-time-lesson', '⚠️Delete time'),
       ('ENG', 'start-init', '😀 Start!'),
       ('ENG', 'adventure', 'Click for adventure! 🚀🚀🚀'),
       ('ENG', 'choose-language', '🪧 Choose your language:'),
       ('ENG', 'monday', 'Monday'),
       ('ENG', 'tuesday', 'Tuesday'),
       ('ENG', 'wednesday', 'Wednesday'),
       ('ENG', 'thursday', 'Thursday'),
       ('ENG', 'friday', 'Friday'),
       ('ENG', 'saturday', 'Saturday');
